/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockSupabaseClient() {
  console.warn("[Supabase] Returning an in-memory mock client to keep the app functional.");

  // Storage for mock users & session in localStorage if window is defined, so logins persist!
  let sessionStore: any = null;
  const usersStore: any[] = [];

  if (typeof window !== "undefined") {
    try {
      const storedSession = localStorage.getItem("mock_supabase_session");
      if (storedSession) sessionStore = JSON.parse(storedSession);
      const storedUsers = localStorage.getItem("mock_supabase_users");
      if (storedUsers) usersStore.push(...JSON.parse(storedUsers));
    } catch (e) {
      console.error("[Supabase Mock] Error reading localStorage", e);
    }
  }

  const listeners = new Set<any>();

  function triggerListeners(event: string, session: any) {
    listeners.forEach((cb) => {
      try {
        cb(event, session);
      } catch (e) {
        console.error(e);
      }
    });
  }

  const auth = {
    onAuthStateChange: (cb: any) => {
      listeners.add(cb);
      // Immediately call with initial state
      setTimeout(() => cb("SIGNED_IN", sessionStore), 0);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              listeners.delete(cb);
            },
          },
        },
      };
    },
    getSession: async () => {
      return { data: { session: sessionStore }, error: null };
    },
    signInWithPassword: async ({ email, password }: any) => {
      // Find user or auto-create one for smoother testing
      let user = usersStore.find((u) => u.email === email);
      if (!user) {
        user = {
          id: Math.random().toString(36).substring(2),
          email,
          user_metadata: { full_name: email.split("@")[0] },
        };
        usersStore.push(user);
        if (typeof window !== "undefined") {
          localStorage.setItem("mock_supabase_users", JSON.stringify(usersStore));
        }
      }

      sessionStore = {
        access_token: "mock-token-" + Math.random().toString(36).substring(2),
        user,
      };

      if (typeof window !== "undefined") {
        localStorage.setItem("mock_supabase_session", JSON.stringify(sessionStore));
      }

      triggerListeners("SIGNED_IN", sessionStore);
      return { data: { user, session: sessionStore }, error: null };
    },
    signUp: async ({ email, password, options }: any) => {
      const user = {
        id: Math.random().toString(36).substring(2),
        email,
        user_metadata: { full_name: options?.data?.full_name || email.split("@")[0] },
      };
      usersStore.push(user);
      sessionStore = {
        access_token: "mock-token-" + Math.random().toString(36).substring(2),
        user,
      };
      if (typeof window !== "undefined") {
        localStorage.setItem("mock_supabase_users", JSON.stringify(usersStore));
        localStorage.setItem("mock_supabase_session", JSON.stringify(sessionStore));
      }
      triggerListeners("SIGNED_IN", sessionStore);
      return { data: { user, session: sessionStore }, error: null };
    },
    signOut: async () => {
      sessionStore = null;
      if (typeof window !== "undefined") {
        localStorage.removeItem("mock_supabase_session");
      }
      triggerListeners("SIGNED_OUT", null);
      return { error: null };
    },
    signInMock: async (email: string, name: string) => {
      let user = usersStore.find((u) => u.email === email);
      if (!user) {
        user = {
          id: Math.random().toString(36).substring(2),
          email,
          user_metadata: { full_name: name },
        };
        usersStore.push(user);
        if (typeof window !== "undefined") {
          localStorage.setItem("mock_supabase_users", JSON.stringify(usersStore));
        }
      } else {
        user.user_metadata = { ...user.user_metadata, full_name: name };
      }

      sessionStore = {
        access_token: "mock-token-" + Math.random().toString(36).substring(2),
        user,
      };

      if (typeof window !== "undefined") {
        localStorage.setItem("mock_supabase_session", JSON.stringify(sessionStore));
      }

      triggerListeners("SIGNED_IN", sessionStore);
      return { data: { user, session: sessionStore }, error: null };
    },
  };

  const queryProxy: any = () => {
    const chain = {
      select: () => chain,
      insert: () => chain,
      update: () => chain,
      delete: () => chain,
      eq: () => chain,
      single: () => chain,
      then: (onfulfilled: any) => Promise.resolve(onfulfilled({ data: [], error: null })),
    };
    return chain;
  };

  return {
    auth,
    from: () => queryProxy(),
    rpc: () => Promise.resolve({ data: null, error: null }),
  } as any;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "[Supabase] Missing environment variables. Falling back to in-memory mock client.",
    );
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
