/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AideRouteImport } from './routes/aide'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as ProposerProjetRouteImport } from './routes/proposer-projet'
import { Route as SavoirRouteImport } from './routes/savoir'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposerProjetRoute = ProposerProjetRouteImport.update({
  id: '/proposer-projet',
  path: '/proposer-projet',
  getParentRoute: () => rootRouteImport,
} as any)
const SavoirRoute = SavoirRouteImport.update({
  id: '/savoir',
  path: '/savoir',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/catalogue': typeof CatalogueRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/parametres': typeof ParametresRoute
  '/projets': typeof ProjetsRoute
  '/proposer-projet': typeof ProposerProjetRoute
  '/savoir': typeof SavoirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/catalogue': typeof CatalogueRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/parametres': typeof ParametresRoute
  '/projets': typeof ProjetsRoute
  '/proposer-projet': typeof ProposerProjetRoute
  '/savoir': typeof SavoirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/catalogue': typeof CatalogueRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/parametres': typeof ParametresRoute
  '/projets': typeof ProjetsRoute
  '/proposer-projet': typeof ProposerProjetRoute
  '/savoir': typeof SavoirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aide'
    | '/catalogue'
    | '/connexion'
    | '/dashboard'
    | '/parametres'
    | '/projets'
    | '/proposer-projet'
    | '/savoir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aide'
    | '/catalogue'
    | '/connexion'
    | '/dashboard'
    | '/parametres'
    | '/projets'
    | '/proposer-projet'
    | '/savoir'
  id:
    | '__root__'
    | '/'
    | '/aide'
    | '/catalogue'
    | '/connexion'
    | '/dashboard'
    | '/parametres'
    | '/projets'
    | '/proposer-projet'
    | '/savoir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AideRoute: typeof AideRoute
  CatalogueRoute: typeof CatalogueRoute
  ConnexionRoute: typeof ConnexionRoute
  DashboardRoute: typeof DashboardRoute
  ParametresRoute: typeof ParametresRoute
  ProjetsRoute: typeof ProjetsRoute
  ProposerProjetRoute: typeof ProposerProjetRoute
  SavoirRoute: typeof SavoirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposer-projet': {
      id: '/proposer-projet'
      path: '/proposer-projet'
      fullPath: '/proposer-projet'
      preLoaderRoute: typeof ProposerProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savoir': {
      id: '/savoir'
      path: '/savoir'
      fullPath: '/savoir'
      preLoaderRoute: typeof SavoirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AideRoute: AideRoute,
  CatalogueRoute: CatalogueRoute,
  ConnexionRoute: ConnexionRoute,
  DashboardRoute: DashboardRoute,
  ParametresRoute: ParametresRoute,
  ProjetsRoute: ProjetsRoute,
  ProposerProjetRoute: ProposerProjetRoute,
  SavoirRoute: SavoirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
