import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.courses": "Formations",
    "nav.projects": "Projets",
    "nav.savoir": "Savoir+",
    "nav.dashboard": "Tableau de bord",
    "nav.myDashboard": "Mon tableau de bord",
    "nav.logout": "Se déconnecter",
    "nav.login": "Connexion",
    "nav.signup": "Démarrer",
    "nav.logoutConfirmTitle": "Souhaitez-vous vraiment vous déconnecter ?",
    "nav.logoutConfirmDesc":
      "Vous devrez vous reconnecter pour accéder à vos cours, projets et votre assistant intelligent Savoir+.",
    "nav.cancel": "Annuler",
    "nav.languageLabel": "Langue / Language",
    "nav.notifications": "Notifications",
    "genove.tagline": "Là où l'IA rencontre le sens",

    // Hero & Home
    "hero.badge": "Plateforme EdTech Nouvelle Génération",
    "hero.title1": "L'apprentissage",
    "hero.title2": "Augmenté Par L'intelligence.",
    "hero.subtitle":
      "Genove connecte apprenants, formateurs et partenaires institutionnels autour de formations personnalisées, de projets collaboratifs et d'une IA de confiance.",
    "hero.ctaExplore": "Explorer les formations",
    "hero.ctaDemo": "Voir la démo",
    "hero.trust1": "Certifié Qualiopi",
    "hero.trust2": "Partenaires 40+",
    "hero.trust3": "Note 4.9 / 5",
    "hero.aiBadge": "Personnalisé & alimenté par l'IA",
    "hero.activeCourses": "Formations Actives",
    "hero.ecosystemTag": "L'Écosystème Genove",
    "hero.ecosystemTitle1": "Une plateforme",
    "hero.ecosystemTitle2": "Trois écosystèmes",
    "hero.ecosystemSubtitle": "Chaque acteur trouve son espace, ses outils et ses opportunités.",
    "hero.learners": "Apprenants",
    "hero.learnersDesc": "Parcours personnalisés, mentoring et projets réels pour progresser vite.",
    "hero.trainers": "Formateurs",
    "hero.trainersDesc": "Publier, animer et suivre vos cohortes avec une suite d'outils IA.",
    "hero.partners": "Partenaires",
    "hero.partnersDesc": "Proposez des projets, sourcez les meilleurs talents formés à vos enjeux.",
    "hero.statLearners": "Apprenants actifs",
    "hero.statCourses": "Formations certifiantes",
    "hero.statCompletion": "Taux de complétion",
    "hero.statPartners": "Partenaires institutionnels",

    // Home Sections
    "home.selectionTag": "Sélection Genove",
    "home.recTitle1": "Formations",
    "home.recTitle2": "recommandées",
    "home.recSubtitle": "Choisies par notre IA en fonction des tendances métiers.",
    "home.seeAllCatalogue": "Voir tout le catalogue",
    "home.ongoingTag": "En ce moment",
    "home.projTitle1": "Projets",
    "home.projTitle2": "en cours",
    "home.projSubtitle":
      "Projets d'innovation et réalisations concrètes menés avec nos partenaires.",
    "home.allProjects": "Tous les projets",
    "home.collaborators": "collaborateurs",
    "home.view": "Voir",
    "home.techHeading1": "Des technologies de pointe au service de votre",
    "home.techHeading2": "réussite",
    "home.techSubtitle":
      "Explorez nos piliers technologiques conçus pour accélérer votre apprentissage, vos projets et votre carrière.",
    "home.catTitle": "Catalogue",
    "home.catHighlight": "Intelligent & IA",
    "home.catDesc":
      "Recherche sémantique, filtres avancés et recommandations dynamiques adaptées à votre parcours et aux métiers d'avenir.",
    "home.catCta": "Voir les formations",
    "home.catB1": "Filtres thématiques & niveaux d'expertise",
    "home.catB2": "Score de pertinence IA personnalisé",
    "home.catB3": "Certifications reconnues & Qualiopi",
    "home.projTitle": "Projets",
    "home.projHighlight": "Partenaires & Réalisations",
    "home.projDesc":
      "Découvrez nos projets innovants et études de cas réels développés avec nos entreprises, startups et institutions partenaires.",
    "home.projCta": "Explorer les projets",
    "home.projB1": "Projets concrets en IA, Data, Web, Mobile & Cloud",
    "home.projB2": "Études de cas détaillées avec architectures & résultats",
    "home.projB3": "Solutions sur-mesure co-développées avec nos partenaires",
    "home.savoirTitle": "Savoir+",
    "home.savoirHighlight": "Assistant IA Multi-Agents",
    "home.savoirDesc":
      "Assistant conversationnel enrichi par un pipeline RAG multi-agents connecté aux bases de connaissances vérifiées.",
    "home.savoirCta": "Poser une question",
    "home.savoirB1": "Routage → Recherche → Synthèse rapide",
    "home.savoirB2": "Citations traçables & sources officielles",
    "home.savoirB3": "Historique de conversations sauvegardé",
    "home.preview": "Aperçu interactif",
    "home.clickExplore": "Cliquer pour explorer",
    "home.teamTag": "L'Équipe Fondatrice",
    "home.teamTitle1": "L'Équipe",
    "home.teamTitle2": "Fondatrice",
    "home.teamSubtitle":
      "Une équipe tunisienne passionnée venue de l'EdTech, de la recherche en IA et du design produit.",
    "home.ctaReady": "Prêt à transformer votre apprentissage ?",
    "home.ctaDesc":
      "Rejoignez la communauté Genove et accédez à un écosystème unique de formations, projets et savoir.",
    "home.ctaFree": "Commencer gratuitement",
    "home.ctaTalk": "Parler à l'IA",

    // Catalogue
    "cat.badge": "Catalogue de formations",
    "cat.heroTitle1": "Formations certifiantes &",
    "cat.heroTitle2": "parcours d'excellence",
    "cat.heroSubtitle":
      "Recherche sémantique, filtres thématiques et cours guidés par des experts et l'IA Genove.",
    "cat.searchPlaceholder": "Rechercher une formation, une compétence, une technologie...",
    "cat.filters": "Filtres",
    "cat.allThemes": "Toutes les thématiques",
    "cat.allLevels": "Tous les niveaux",
    "cat.clearFilters": "Effacer les filtres",
    "cat.coursesFound": "formation(s) trouvée(s)",
    "cat.explore": "Explorer la formation",
    "cat.enrolled": "Inscrit",
    "cat.enroll": "S'inscrire à cette formation",
    "cat.back": "Retour au catalogue",
    "cat.overview": "Aperçu de la formation",
    "cat.syllabus": "Programme",
    "cat.objectives": "Objectifs",
    "cat.prerequisites": "Prérequis",
    "cat.skills": "Compétences visées",
    "cat.instructor": "Formateur",
    "cat.reviews": "Avis apprenants",
    "cat.faq": "FAQ & Questions",
    "cat.resources": "Ressources téléchargeables",

    "catalogue.tag": "Sélection Genove",
    "catalogue.title1": "Catalogue de",
    "catalogue.title2": "formations",
    "catalogue.subtitle":
      "Explorez plus de 120+ formations certifiantes propulsées par l'IA et conçues par des experts du secteur. Développez des compétences pratiques et obtenez des certifiats reconnus.",
    "catalogue.searchPlaceholder":
      "Rechercher parmi nos 120+ formations certifiantes (ex: IA, Data, Python, AWS, UX Design)...",
    "catalogue.searchPlaceholderMobile": "Rechercher une formation",
    "catalogue.showFilters": "Afficher les filtres",
    "catalogue.hideFilters": "Masquer les filtres",
    "catalogue.filters": "Filtres",
    "catalogue.theme": "Thématique",
    "catalogue.level": "Niveau",
    "catalogue.reset": "Réinitialiser",
    "catalogue.availableCourses": "formations disponibles",
    "catalogue.noResults": "Aucune formation ne correspond",
    "catalogue.tryModify": "Essayez de modifier vos filtres de recherche.",
    "catalogue.registered": "inscrits",
    "catalogue.view": "Voir",
    "catalogue.home": "Accueil",
    "catalogue.coursesTitle": "Formations",
    "catalogue.backToCat": "Retour au catalogue",
    "catalogue.description": "Description",
    "catalogue.objectives": "Objectifs pédagogiques",
    "catalogue.prereqs": "Prérequis",
    "catalogue.skillsAcquired": "Compétences acquises",
    "catalogue.tech": "Technologies",
    "catalogue.prog": "Programme détaillé",
    "catalogue.faqs": "Questions fréquentes",
    "catalogue.reviews": "Avis",
    "catalogue.docs": "Documents & ressources",
    "catalogue.certPreview": "Aperçu du certificat",
    "catalogue.progression": "Votre progression",
    "catalogue.enroll": "S'inscrire",
    "catalogue.favorites": "Favoris",
    "catalogue.share": "Partager",

    // Projets
    "proj.badge": "Réalisations & Partenariats",
    "proj.heroTitle1": "Nos projets & cas d'usage",
    "proj.heroTitle2": "avec nos partenaires",
    "proj.heroSubtitle":
      "Découvrez les solutions concrètes en IA, Data, Web & Cloud co-développées avec nos institutions et entreprises partenaires.",
    "proj.searchPlaceholder": "Rechercher un projet",
    "proj.allDomains": "Tous les domaines",
    "proj.projectsFound": "projet(s) trouvé(s)",
    "proj.viewCase": "Consulter l'étude de cas",
    "proj.propose": "Proposer un projet",
    "proj.context": "Contexte",
    "proj.solution": "Solution déployée",
    "proj.keyFeatures": "Fonctionnalités clés",
    "proj.testimonial": "Témoignage partenaire",

    "projets.heroTag": "Portfolio Genove",
    "projets.heroTitle1": "Nos réalisations avec",
    "projets.heroTitle2": "nos partenaires",
    "projets.heroSubtitle":
      "Genove accompagne entreprises, institutions et organismes dans la conception de solutions innovantes : intelligence artificielle, plateformes web, e-learning, automatisation, data et cloud. Découvrez quelques-unes de nos études de cas.",
    "projets.proposeBtn": "Proposer un projet",
    "projets.contactBtn": "Nous contacter",
    "projets.caseStudiesTag": "Études de cas & Réalisations",
    "projets.ourRealizations": "Nos projets",
    "projets.realized": "réalisés",
    "projets.selectionDesc":
      "Une sélection de solutions innovantes livrées par Genove avec nos partenaires clés (IA, Cloud, Web, Mobile, Data & Automatisation).",
    "projets.certifiedProjects": "Projets Certifiés",
    "projets.tailoredDelivered": "Sur-Mesure & Livrés",
    "projets.multiStack": "IA, Cloud & Web",
    "projets.partnersCount": "Partenaires d'excellence",
    "projets.deployedCount": "Projets Déployés",
    "projets.satisfactionRate": "Satisfaction Partenaires",

    // Savoir+
    "savoir.badge": "Assistant RAG Multi-Agents",
    "savoir.heroTitle": "Prêt à apprendre",
    "savoir.heroSubtitle":
      "Obtenez des réponses vérifiées, sourcées et synthétisées par notre intelligence artificielle.",
    "savoir.inputPlaceholder": "Posez votre question à Genove...",
    "savoir.placeholder": "Posez votre question à Genove...",
    "savoir.send": "Envoyer",
    "savoir.newChat": "Nouvelle discussion",
    "savoir.history": "Historique",
    "savoir.recent": "Discussions récentes",
    "savoir.clearHistory": "Effacer l'historique",
    "savoir.settings": "Paramètres",
    "savoir.pinned": "Épinglés",
    "savoir.suggestions": "Exemples de questions",

    // Footer
    "footer.tagline":
      "Plateforme e-learning intelligente — apprenants, formateurs et partenaires institutionnels réunis autour d'une IA de confiance.",
    "footer.placeholder": "Votre email",
    "footer.subscribe": "S'inscrire",
    "footer.product": "Produit",
    "footer.company": "Entreprise",
    "footer.legal": "Légal",
    "footer.pricing": "Tarifs",
    "footer.about": "À propos",
    "footer.team": "Équipe",
    "footer.careers": "Carrières",
    "footer.press": "Presse",
    "footer.privacy": "Confidentialité",
    "footer.cgu": "CGU",
    "footer.cookies": "Cookies",
    "footer.mentions": "Mentions",
    "footer.soon": "Bientôt",
    "footer.rights": "Tous droits réservés.",
    "footer.location": "Fait avec soin · Tunis",
    "footer.support": "Assistance",
    "footer.helpCenter": "Centre d'aide",
    "footer.contact": "Nous contacter",
    "footer.faq": "FAQ",

    // Auth
    "auth.welcomeBack": "Ravis de vous revoir sur",
    "auth.welcomeSub": "Accédez à vos parcours, vos projets et à l'assistant IA en un clic.",
    "auth.joinUs": "Rejoignez l'écosystème",
    "auth.joinSub":
      "Créez votre compte pour explorer les formations, les projets partenaires et Savoir+.",
    "auth.highlight1": "248 formations certifiantes et parcours sur mesure",
    "auth.highlight2": "Projets collaboratifs avec des partenaires institutionnels",
    "auth.highlight3": "Multi-agent IA assistant pour vous accompagner 24/7",
    "auth.footerPlatform": "Genove — Plateforme e-learning intelligente",
    "auth.backHome": "Retour à l'accueil",
    "auth.loginTitle": "Connexion",
    "auth.signupTitle": "Créer un compte",
    "auth.loginDesc": "Bon retour parmi nous. Entrez vos identifiants pour continuer.",
    "auth.signupDesc": "Quelques secondes suffisent pour démarrer votre parcours.",
    "auth.orWithEmail": "ou avec votre email",
    "auth.firstName": "Prénom",
    "auth.lastName": "Nom",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.rememberMe": "Se souvenir de moi",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.termsLead": "En créant un compte, vous acceptez nos",
    "auth.terms": "Conditions",
    "auth.andOur": "et notre",
    "auth.privacy": "Politique de confidentialité",
    "auth.loginBtn": "Se connecter",
    "auth.signupBtn": "Créer mon compte",
    "auth.pleaseWait": "Veuillez patienter…",
    "auth.newUser": "Nouveau sur Genove ?",
    "auth.alreadyUser": "Déjà un compte ?",
    "auth.createAccount": "Créer un compte",
    "auth.signIn": "Se connecter",
    "auth.errEmailPass": "Merci de renseigner votre email et mot de passe.",
    "auth.errFirstLast": "Merci de renseigner votre nom et prénom.",
    "auth.errPassLength": "Le mot de passe doit contenir au moins 6 caractères.",
    "auth.errPassMismatch": "Les mots de passe ne correspondent pas.",
    "auth.successSignup": "Compte créé avec succès ! Redirection en cours...",

    // Dashboard
    "dash.badge": "Espace R&D & Innovation",
    "dash.title": "Tableau de bord",
    "dash.hello": "Bonjour",
    "dash.welcomeSub":
      "Vous avez des travaux en cours. Parmi eux : 2 projets R&D, 3 cours de formation et 2 maquettes validées. Le travail de la semaine est excellent, déjà en progression à 70%.",
    "dash.myProfile": "Mon profil",
    "dash.yourProgress": "70% Vos progrès",
    "dash.progress70": "Progression 70%",
    "dash.dateRange": "Août - Déc 2026",
    "dash.editAvatar": "Modifier la photo de profil",
    "dash.editAvatarSub": "Personnalisez votre avatar ou téléchargez une photo",
    "dash.livePreview": "Aperçu direct",
    "dash.uploadDevice": "Télécharger une photo depuis votre appareil",
    "dash.orPasteUrl": "Ou collez l'URL d'une image :",
    "dash.orChooseSuggested": "Ou choisissez un avatar suggéré :",
    "dash.cancel": "Annuler",
    "dash.savePhoto": "Enregistrer la photo",
    "dash.saving": "Enregistrement...",
    "dash.activity": "Activité",
    "dash.daily": "Quotidien",
    "dash.weekly": "Hebdomadaire",
    "dash.progress": "Progression",
    "dash.thisWeek": "Cette semaine",
    "dash.team": "Équipe",
    "dash.client": "Clients",
    "dash.today": "Aujourd'hui",
    "dash.viewAll": "Tout voir",
    "dash.designSystem": "Système de Design",
    "dash.designSystemSub": "Créer un design pour un nouveau projet",
    "dash.mockupLanding": "Maquette Page d'Accueil",
    "dash.mockupLandingSub": "Nouvelle page de présentation",
    "dash.layoutTask": "Mise en page",
    "dash.layoutTaskSub": "Créer une nouvelle disposition graphique",
    "dash.graphicDesigner": "Designer Graphique",
    "dash.developer": "Développement",
    "dash.project": "Projets",
    "dash.userProject": "de l'utilisateur",
    "dash.userProjectSub": "Projet R&D",
    "dash.baselineDesc":
      "Développement d'un système prédictif pour le diagnostic médical et suivi des patients.",
    "dash.paperDesc":
      "Architecture microservices pour la gestion de données industrielles et objets connectés.",
    "dash.paperIndustryDesc":
      "Architecture microservices pour la gestion de données industrielles et objets connectés.",
    "dash.toolDesc": "Modèle de traitement de langage naturel et analyse automatisée des rapports.",
    "dash.toolProductionDesc":
      "Modèle de traitement de langage naturel et analyse automatisée des rapports.",
    "dash.recentActivity": "Dernières activités",
    "dash.courseProgress": "Progression des cours",
    "dash.skillsBadges": "Compétences & Badges",
    "dash.obtainedBadges": "Badges obtenus",
    "dash.aiRecs": "Recommandations IA",
    "dash.deadlines": "Échéances importantes",
    "dash.internships": "Mes candidatures de stage",
    "dash.inProgress": "en cours",
    "dash.sidebarPlatform": "Plateforme R&D",
    "dash.sidebarAddProject": "Proposer un projet R&D",
    "dash.sidebarCollapse": "Réduire le menu",
    "dash.sidebarDashboard": "Tableau de bord",
    "dash.sidebarProjects": "Projets R&D",
    "dash.sidebarCourses": "Formations",
    "dash.sidebarSettings": "Paramètres",
    "dash.sidebarHelp": "Aide & Support",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.courses": "Courses",
    "nav.projects": "Projects",
    "nav.savoir": "Savoir+",
    "nav.dashboard": "Dashboard",
    "nav.myDashboard": "My Dashboard",
    "nav.logout": "Log out",
    "nav.login": "Sign in",
    "nav.signup": "Get Started",
    "nav.logoutConfirmTitle": "Are you sure you want to log out?",
    "nav.logoutConfirmDesc":
      "You will need to sign back in to access your courses, projects, and Savoir+ AI assistant.",
    "nav.cancel": "Cancel",
    "nav.languageLabel": "Language",
    "nav.notifications": "Notifications",
    "genove.tagline": "Where AI meets purpose",

    // Hero & Home
    "hero.badge": "Next-Gen EdTech Platform",
    "hero.title1": "Learning Augmented",
    "hero.title2": "By Intelligence.",
    "hero.subtitle":
      "Genove connects learners, trainers, and institutional partners around personalized training, collaborative projects, and trusted AI.",
    "hero.ctaExplore": "Explore Courses",
    "hero.ctaDemo": "Watch Demo",
    "hero.trust1": "Qualiopi Certified",
    "hero.trust2": "40+ Partners",
    "hero.trust3": "Rating 4.9 / 5",
    "hero.aiBadge": "Personalized & AI-powered",
    "hero.activeCourses": "Active Courses",
    "hero.ecosystemTag": "The Genove Ecosystem",
    "hero.ecosystemTitle1": "One platform,",
    "hero.ecosystemTitle2": "Three ecosystems",
    "hero.ecosystemSubtitle": "Every stakeholder finds their workspace, tools, and opportunities.",
    "hero.learners": "Learners",
    "hero.learnersDesc": "Personalized paths, mentoring, and real-world projects to grow fast.",
    "hero.trainers": "Trainers",
    "hero.trainersDesc": "Publish, lead, and monitor your cohorts with an AI suite.",
    "hero.partners": "Partners",
    "hero.partnersDesc": "Offer real projects, source top talent trained for your needs.",
    "hero.statLearners": "Active Learners",
    "hero.statCourses": "Certified Courses",
    "hero.statCompletion": "Completion Rate",
    "hero.statPartners": "Institutional Partners",

    // Home Sections
    "home.selectionTag": "Genove Selection",
    "home.recTitle1": "Recommended",
    "home.recTitle2": "Courses",
    "home.recSubtitle": "Handpicked by our AI based on current industry trends.",
    "home.seeAllCatalogue": "View full catalogue",
    "home.ongoingTag": "Trending Now",
    "home.projTitle1": "Ongoing",
    "home.projTitle2": "Projects",
    "home.projSubtitle": "Innovation projects and practical solutions led with our partners.",
    "home.allProjects": "All projects",
    "home.collaborators": "collaborators",
    "home.view": "View",
    "home.techHeading1": "Cutting-edge technologies powering your",
    "home.techHeading2": "success",
    "home.techSubtitle":
      "Explore our technological pillars built to accelerate your learning, projects, and career.",
    "home.catTitle": "Catalogue",
    "home.catHighlight": "Smart & AI-Powered",
    "home.catDesc":
      "Semantic search, advanced filters, and dynamic recommendations matched to your path and future careers.",
    "home.catCta": "View courses",
    "home.catB1": "Thematic filters & expertise levels",
    "home.catB2": "Personalized AI relevance score",
    "home.catB3": "Recognized & Qualiopi certifications",
    "home.projTitle": "Projects",
    "home.projHighlight": "Partners & Case Studies",
    "home.projDesc":
      "Discover our innovative projects and real-world case studies developed with corporate and institutional partners.",
    "home.projCta": "Explore projects",
    "home.projB1": "Concrete projects in AI, Data, Web, Mobile & Cloud",
    "home.projB2": "Detailed case studies with architecture & outcomes",
    "home.projB3": "Tailored solutions co-developed with partners",
    "home.savoirTitle": "Savoir+",
    "home.savoirHighlight": "Multi-Agent AI Assistant",
    "home.savoirDesc":
      "Conversational assistant powered by a multi-agent RAG pipeline connected to verified knowledge bases.",
    "home.savoirCta": "Ask a question",
    "home.savoirB1": "Routing → Search → Fast Synthesis",
    "home.savoirB2": "Traceable citations & official sources",
    "home.savoirB3": "Saved conversation history",
    "home.preview": "Interactive preview",
    "home.clickExplore": "Click to explore",
    "home.teamTag": "The Founding Team",
    "home.teamTitle1": "The Founding",
    "home.teamTitle2": "Team",
    "home.teamSubtitle": "A passionate Tunisian team from EdTech, AI research, and product design.",
    "home.ctaReady": "Ready to transform your learning?",
    "home.ctaDesc":
      "Join the Genove community and access a unique ecosystem of courses, projects, and knowledge.",
    "home.ctaFree": "Start for free",
    "home.ctaTalk": "Talk to AI",

    // Catalogue
    "cat.badge": "Course Catalogue",
    "cat.heroTitle1": "Certified Courses &",
    "cat.heroTitle2": "Excellence Paths",
    "cat.heroSubtitle": "Semantic search, topic filters, and expert/AI-guided courses.",
    "cat.searchPlaceholder": "Search for a course, skill, technology...",
    "cat.filters": "Filters",
    "cat.allThemes": "All topics",
    "cat.allLevels": "All levels",
    "cat.clearFilters": "Clear filters",
    "cat.coursesFound": "course(s) found",
    "cat.explore": "Explore course",
    "cat.enrolled": "Enrolled",
    "cat.enroll": "Enroll in this course",
    "cat.back": "Back to catalogue",
    "cat.overview": "Course Overview",
    "cat.syllabus": "Syllabus",
    "cat.objectives": "Objectives",
    "cat.prerequisites": "Prerequisites",
    "cat.skills": "Target Skills",
    "cat.instructor": "Instructor",
    "cat.reviews": "Learner Reviews",
    "cat.faq": "FAQ & Questions",
    "cat.resources": "Downloadable Resources",

    "catalogue.tag": "Genove Selection",
    "catalogue.title1": "Course",
    "catalogue.title2": "Catalogue",
    "catalogue.subtitle":
      "Explore 120+ certified courses powered by AI and designed by industry experts. Gain hands-on skills and earn recognized credentials.",
    "catalogue.searchPlaceholder":
      "Search 120+ certified courses (e.g. AI, Data, Python, AWS, UX Design)...",
    "catalogue.searchPlaceholderMobile": "Search courses",
    "catalogue.showFilters": "Show filters",
    "catalogue.hideFilters": "Hide filters",
    "catalogue.filters": "Filters",
    "catalogue.theme": "Topic",
    "catalogue.level": "Level",
    "catalogue.reset": "Reset",
    "catalogue.availableCourses": "available courses",
    "catalogue.noResults": "No courses matched your search",
    "catalogue.tryModify": "Try adjusting your search filters.",
    "catalogue.registered": "enrolled",
    "catalogue.view": "View",
    "catalogue.home": "Home",
    "catalogue.coursesTitle": "Courses",
    "catalogue.backToCat": "Back to catalogue",
    "catalogue.description": "Description",
    "catalogue.objectives": "Learning Objectives",
    "catalogue.prereqs": "Prerequisites",
    "catalogue.skillsAcquired": "Skills Acquired",
    "catalogue.tech": "Technologies",
    "catalogue.prog": "Detailed Curriculum",
    "catalogue.faqs": "Frequently Asked Questions",
    "catalogue.reviews": "Reviews",
    "catalogue.docs": "Documents & Resources",
    "catalogue.certPreview": "Certificate Preview",
    "catalogue.progression": "Your progress",
    "catalogue.enroll": "Enroll",
    "catalogue.favorites": "Favorites",
    "catalogue.share": "Share",

    // Projets
    "proj.badge": "Projects & Partnerships",
    "proj.heroTitle1": "Our Projects & Case Studies",
    "proj.heroTitle2": "with Our Partners",
    "proj.heroSubtitle":
      "Discover real-world solutions in AI, Data, Web & Cloud co-developed with partner institutions and companies.",
    "proj.searchPlaceholder": "Search a project",
    "proj.allDomains": "All domains",
    "proj.projectsFound": "project(s) found",
    "proj.viewCase": "View case study",
    "proj.propose": "Propose a project",
    "proj.context": "Context",
    "proj.solution": "Deployed Solution",
    "proj.keyFeatures": "Key Features",
    "proj.testimonial": "Partner Testimonial",

    "projets.heroTag": "Genove Portfolio",
    "projets.heroTitle1": "Our Projects with",
    "projets.heroTitle2": "Our Partners",
    "projets.heroSubtitle":
      "Genove supports companies, institutions, and organizations in designing innovative solutions: AI, web platforms, e-learning, automation, data, and cloud. Discover some of our case studies.",
    "projets.proposeBtn": "Propose a project",
    "projets.contactBtn": "Contact us",
    "projets.caseStudiesTag": "Case Studies & Projects",
    "projets.ourRealizations": "Our Completed",
    "projets.realized": "Projects",
    "projets.selectionDesc":
      "A selection of innovative solutions delivered by Genove with key partners (AI, Cloud, Web, Mobile, Data & Automation).",
    "projets.certifiedProjects": "Certified Projects",
    "projets.tailoredDelivered": "Tailored & Delivered",
    "projets.multiStack": "AI, Cloud & Web",
    "projets.partnersCount": "Partners of Excellence",
    "projets.deployedCount": "Projects Deployed",
    "projets.satisfactionRate": "Partner Satisfaction",

    // Savoir+
    "savoir.badge": "Multi-Agent RAG Assistant",
    "savoir.heroTitle": "Ready to learn",
    "savoir.heroSubtitle": "Get verified, sourced, and synthesized answers powered by AI.",
    "savoir.inputPlaceholder": "Ask Genove anything...",
    "savoir.placeholder": "Ask Genove anything...",
    "savoir.send": "Send",
    "savoir.newChat": "New Chat",
    "savoir.history": "History",
    "savoir.recent": "Recent Discussions",
    "savoir.clearHistory": "Clear History",
    "savoir.settings": "Settings",
    "savoir.pinned": "Pinned",
    "savoir.suggestions": "Sample Questions",

    // Footer
    "footer.tagline":
      "Intelligent e-learning platform — learners, trainers, and institutional partners united around trusted AI.",
    "footer.placeholder": "Your email",
    "footer.subscribe": "Subscribe",
    "footer.product": "Product",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.pricing": "Pricing",
    "footer.about": "About us",
    "footer.team": "Team",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.privacy": "Privacy Policy",
    "footer.cgu": "Terms of Use",
    "footer.cookies": "Cookies",
    "footer.mentions": "Legal Notice",
    "footer.soon": "Soon",
    "footer.support": "Support",
    "footer.helpCenter": "Help Center",
    "footer.contact": "Contact Us",
    "footer.faq": "FAQ",
    "footer.rights": "All rights reserved.",
    "footer.location": "Made with care · Tunis",

    // Auth
    "auth.welcomeBack": "Welcome back to",
    "auth.welcomeSub": "Access your learning paths, projects, and AI assistant in one click.",
    "auth.joinUs": "Join the",
    "auth.joinSub": "Create your account to explore courses, partner projects, and Savoir+.",
    "auth.highlight1": "248 certified courses and tailored learning paths",
    "auth.highlight2": "Collaborative projects with institutional partners",
    "auth.highlight3": "Multi-agent AI assistant to guide you 24/7",
    "auth.footerPlatform": "Genove — Smart E-learning Platform",
    "auth.backHome": "Back to home",
    "auth.loginTitle": "Sign In",
    "auth.signupTitle": "Create an Account",
    "auth.loginDesc": "Welcome back. Enter your credentials to continue.",
    "auth.signupDesc": "Takes just a few seconds to kickstart your journey.",
    "auth.orWithEmail": "or with your email",
    "auth.firstName": "First name",
    "auth.lastName": "Last name",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.termsLead": "By creating an account, you agree to our",
    "auth.terms": "Terms of Service",
    "auth.andOur": "and our",
    "auth.privacy": "Privacy Policy",
    "auth.loginBtn": "Sign In",
    "auth.signupBtn": "Create Account",
    "auth.pleaseWait": "Please wait…",
    "auth.newUser": "New to Genove?",
    "auth.alreadyUser": "Already have an account?",
    "auth.createAccount": "Create an account",
    "auth.signIn": "Sign in",
    "auth.errEmailPass": "Please fill in your email and password.",
    "auth.errFirstLast": "Please fill in your first and last name.",
    "auth.errPassLength": "Password must contain at least 6 characters.",
    "auth.errPassMismatch": "Passwords do not match.",
    "auth.successSignup": "Account created successfully! Redirecting...",

    // Dashboard
    "dash.badge": "R&D & Innovation Hub",
    "dash.title": "Dashboard",
    "dash.hello": "Hello",
    "dash.welcomeSub":
      "You have active work in progress: 2 R&D projects, 3 training courses, and 2 approved mockups. Excellent work this week, already at 70% progress.",
    "dash.myProfile": "My Profile",
    "dash.yourProgress": "70% Your Progress",
    "dash.progress70": "70% Progress",
    "dash.dateRange": "Aug - Dec 2026",
    "dash.editAvatar": "Change profile picture",
    "dash.editAvatarSub": "Customize your avatar or upload a picture",
    "dash.livePreview": "Live preview",
    "dash.uploadDevice": "Upload a photo from your device",
    "dash.orPasteUrl": "Or paste an image URL:",
    "dash.orChooseSuggested": "Or pick a suggested avatar:",
    "dash.cancel": "Cancel",
    "dash.savePhoto": "Save picture",
    "dash.saving": "Saving...",
    "dash.activity": "Activity",
    "dash.daily": "Daily",
    "dash.weekly": "Weekly",
    "dash.progress": "Progress",
    "dash.thisWeek": "This Week",
    "dash.team": "Team",
    "dash.client": "Clients",
    "dash.today": "Today",
    "dash.viewAll": "View All",
    "dash.designSystem": "Design System",
    "dash.designSystemSub": "Create design for new project",
    "dash.mockupLanding": "Mockup Landing Page",
    "dash.mockupLandingSub": "Landing in new page",
    "dash.layoutTask": "Layout",
    "dash.layoutTaskSub": "Make a new design layout",
    "dash.graphicDesigner": "Graphic Designer",
    "dash.developer": "Development",
    "dash.project": "Projects",
    "dash.userProject": "user project",
    "dash.userProjectSub": "R&D Project",
    "dash.baselineDesc":
      "Development of a predictive system for medical diagnosis and patient tracking.",
    "dash.paperDesc":
      "Microservices architecture for industrial data management and connected devices.",
    "dash.paperIndustryDesc":
      "Microservices architecture for industrial data management and connected devices.",
    "dash.toolDesc": "Natural language processing model and automated report analysis.",
    "dash.toolProductionDesc": "Natural language processing model and automated report analysis.",
    "dash.recentActivity": "Recent Activity",
    "dash.courseProgress": "Course Progress",
    "dash.skillsBadges": "Skills & Badges",
    "dash.obtainedBadges": "Obtained badges",
    "dash.aiRecs": "AI Recommendations",
    "dash.deadlines": "Important Deadlines",
    "dash.internships": "My Internship Applications",
    "dash.inProgress": "in progress",
    "dash.sidebarPlatform": "R&D Platform",
    "dash.sidebarAddProject": "Propose an R&D Project",
    "dash.sidebarCollapse": "Collapse menu",
    "dash.sidebarDashboard": "Dashboard",
    "dash.sidebarProjects": "R&D Projects",
    "dash.sidebarCourses": "Courses",
    "dash.sidebarSettings": "Settings",
    "dash.sidebarHelp": "Help & Support",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    if (typeof window !== "undefined" && typeof localStorage !== "undefined") {
      try {
        const saved = localStorage.getItem("genove_language") as Language;
        if (saved && (saved === "fr" || saved === "en")) {
          setLanguageState(saved);
        } else {
          localStorage.setItem("genove_language", "en");
        }
      } catch {
        // ignore
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined" && typeof localStorage !== "undefined") {
      try {
        localStorage.setItem("genove_language", lang);
      } catch {
        // ignore
      }
    }
  };

  const t = (key: string): string => {
    return (
      translations[language]?.[key] || translations["en"]?.[key] || translations["fr"]?.[key] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
